CREATE TABLE agr(
    id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	age INT NOT NULL,
	city VARCHAR(100) NOT NULL,
	state VARCHAR(100) NOT NULL,
	pincode INT NOT NULL
);
INSERT INTO agr VALUES(103,'SOURABH SHIROTI',48,'PUNE','MAHARASHTRA','52452');
INSERT INTO agr VALUES(104,'ADAM',18,'AGRA','UTTAR-PRADESH','474101');
INSERT INTO agr VALUES(101,'BOB',28,'PUNE','MADHYA-PRADESH','566201');
INSERT INTO agr VALUES(108,'CASEY',21,'NOIDA','DELHI','154800');
INSERT INTO agr VALUES(109,'DONALD',38,'HYDRABAD','TELANGANA','123252');
INSERT INTO agr VALUES(107,'EMERCY',23,'BAKOLI','DELHI','110036');

SELECT COUNT(name) FROM agr;

SELECT SUM(id) FROM agr;

SELECT AVG(id) FROM agr;

SELECT MAX(age) FROM agr;

SELECT MIN(age) FROM agr;
